
# sudo docker-compose -f docker-compose.yml up
version: "3"
services:
    db:
        image: mysql:8.0.21
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: BMInjection
        volumes:
            - ./db/entry:/docker-entrypoint-initdb.d/:ro
        networks:
            - backend
    app:
        image: flask-app
        container_name: app-backend
        build: 
            dockerfile: Dockerfile.app
        depends_on:
            - db
        links:
            - db
        ports:
            - 80:8000
        networks:
            - backend

networks:
    backend: